name: Static Analysis

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  phpstan:
    name: PHPStan (PHP 8.5)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, xml, ctype, json, openssl, zip, :glfw
          tools: composer:v2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y php-dev build-essential cmake libglfw3-dev xvfb libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev gdb

      - name: Build php-glfw
        run: >
          git clone https://github.com/mario-deluna/php-glfw &&
          cd php-glfw &&
          sudo phpize &&
          ./configure --enable-glfw &&
          make -j$(nproc) &&
          sudo make install &&
          cd ../ &&
          grep -qxF 'extension=glfw.so' /etc/php/8.5/cli/php.ini ||
          echo 'extension=glfw.so' >> /etc/php/8.5/cli/php.ini

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.5-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.5-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --ignore-platform-req=ext-glfw

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --memory-limit=1G --error-format=github

